name: belajar_coding
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter
  http: ^1.2.2 # Tambahkan dependency http di sini
  cupertino_icons: ^1.0.8
  mqtt_client: ^9.6.1 # Tambahkan library mqtt_client

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/image/ # Folder gambar Anda
   
